// AppsForHire — Customer Portal Config
const CUSTOMER = {
  name:          "The Build Company",
  tier:          "starter",
  since:         "March 2026",
  support_email: "cosmicwombat@gmail.com",
  stripe_portal: "https://billing.stripe.com/p/login/YOUR_PORTAL_LINK",
  apps: [
    {
      name:        "Daily Word — Sacred Wisdom",
      description: "",
      url:         "https://dailyword.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "WebPhone",
      description: "",
      url:         "https://webphone.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "The Quake Whisperer",
      description: "",
      url:         "https://theghostkitchen.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "insult me",
      description: "",
      url:         "https://insultme.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Job Tracker + Admin",
      description: "",
      url:         "https://buildco-splitview.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Ghost Book",
      description: "",
      url:         "https://ghostbook-splitview.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Voice Architect",
      description: "",
      url:         "https://voice-architect.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Realtor Radar",
      description: "",
      url:         "https://realtorradar.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Ark Station",
      description: "",
      url:         "https://arkstation.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "The Holy Beastiary",
      description: "",
      url:         "https://holybeastiary.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Guardian Shield Log Analyzer",
      description: "",
      url:         "https://guardianshield.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "My Voice",
      description: "",
      url:         "https://myvoice.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Build Company Portal",
      description: "",
      url:         "https://buildco.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Daily Offerations",
      description: "",
      url:         "https://thegatheringplace.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Salish Shaker",
      description: "",
      url:         "https://tgpquake.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Daily Word",
      description: "",
      url:         "https://tgpscripture.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Is it open",
      description: "",
      url:         "https://isitopen.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Gathering Place Portal",
      description: "",
      url:         "https://gatheringplace.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Random Sentence Generator",
      description: "",
      url:         "https://theghostinterpreter.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Ghost Story Generator",
      description: "",
      url:         "https://tgihorror.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Ghost Interpreter Portal",
      description: "",
      url:         "https://ghostinterpreter.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Fiber Pricing",
      description: "",
      url:         "https://fiberpricing.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Black Sheep Portal",
      description: "",
      url:         "https://blacksheep.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Island Pulse",
      description: "",
      url:         "https://islandpulse.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Lummi Island Portal",
      description: "",
      url:         "https://lummi-island.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "LummiComm",
      description: "",
      url:         "https://lummicomm.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Forge & Fable",
      description: "",
      url:         "https://forgefable.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Radish Tricks Portal",
      description: "",
      url:         "https://radishtricks.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "homescout",
      description: "",
      url:         "https://homescout.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Realty Radar",
      description: "",
      url:         "https://realty-radar.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "The Gathering Planner",
      description: "",
      url:         "https://gathering-planner.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "June 2026",
    }
  ]
};
